import type { ResourceKind, TheoryResource } from "./types";

// ── Curated resource registry for the Agentic AI section ────────────────────
// Every external link in the section lives here exactly once. Topic files and
// the roadmap reference entries by key (`resources: [R.reactPaper, ...]`), so a
// typo is a compile error rather than a dead link, and a URL that moves only
// has to be fixed in one place.
//
// Link-checked 2026-10-08: each URL returned 200 with a page title matching the
// entry, or sits behind a bot wall that blocks scripted checks but is a stable,
// well-known address (huggingface.co, openai.com, oreilly.com, kaggle.com).
// Redirects were replaced with their final destination — notably the
// LangChain/LangGraph docs (now docs.langchain.com), Google ADK (now adk.dev),
// DeepLearning.AI courses (/short-courses/ → /courses/) and Claude docs.
//
// `essential` marks the short "start here" list. Order within each kind is
// roughly "read this first" → "reference".

export const R = {
  // ── Start here ────────────────────────────────────────────────────────────
  buildingEffectiveAgents: {
    title: "Building Effective Agents",
    url: "https://www.anthropic.com/engineering/building-effective-agents",
    kind: "guide",
    source: "Anthropic",
    year: 2024,
    note: "The best single starting point: workflows vs agents, five composable patterns, and why the simplest design that works usually wins.",
    essential: true,
  },
  openaiPracticalGuide: {
    title: "A Practical Guide to Building Agents",
    url: "https://cdn.openai.com/business-guides-and-resources/a-practical-guide-to-building-agents.pdf",
    kind: "guide",
    source: "OpenAI",
    year: 2025,
    note: "A short PDF on when an agent is warranted, single- vs multi-agent orchestration, and layered guardrails — the complement to Anthropic's guide.",
    essential: true,
  },
  reactPaper: {
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    url: "https://arxiv.org/abs/2210.03629",
    kind: "paper",
    source: "Yao et al.",
    year: 2022,
    note: "The Thought → Action → Observation loop that nearly every tool-using agent still runs. Short and foundational.",
    essential: true,
  },
  wengAgents: {
    title: "LLM Powered Autonomous Agents",
    url: "https://lilianweng.github.io/posts/2023-06-23-agent/",
    kind: "guide",
    source: "Lilian Weng",
    year: 2023,
    note: "The classic map of the field — planning, memory and tool use — with the research lineage behind each component.",
    essential: true,
  },
  huyenAgents: {
    title: "Agents",
    url: "https://huyenchip.com/2025/01/07/agents.html",
    kind: "guide",
    source: "Chip Huyen",
    year: 2025,
    note: "A rigorous practitioner's chapter on tools, planning, failure modes and evaluating agents, adapted from her book AI Engineering.",
    essential: true,
  },
  contextEngineering: {
    title: "Effective Context Engineering for AI Agents",
    url: "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "Context as a finite attention budget, and how to spend it: compaction, structured notes, sub-agents, just-in-time retrieval.",
    essential: true,
  },
  demystifyingEvals: {
    title: "Demystifying Evals for AI Agents",
    url: "https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents",
    kind: "guide",
    source: "Anthropic",
    year: 2026,
    note: "Tasks, trials, graders, pass@k vs pass^k, and an eight-step process for building agent evals that actually drive decisions.",
    essential: true,
  },
  buildAnAgent: {
    title: "How to Build an Agent",
    url: "https://ampcode.com/notes/how-to-build-an-agent",
    kind: "guide",
    source: "Thorsten Ball (Amp)",
    year: 2025,
    note: "A working code-editing agent in a few hundred lines of Go — proof that the core is an LLM, a loop and a handful of tools.",
    essential: true,
  },
  hfAgentsCourse: {
    title: "AI Agents Course",
    url: "https://huggingface.co/learn/agents-course/unit0/introduction",
    kind: "course",
    source: "Hugging Face",
    year: 2025,
    note: "Free and hands-on: agent fundamentals, then smolagents, LlamaIndex and LangGraph, ending in a graded capstone agent.",
    essential: true,
  },
  ngAgenticAI: {
    title: "Agentic AI",
    url: "https://www.deeplearning.ai/courses/agentic-ai",
    kind: "course",
    source: "DeepLearning.AI (Andrew Ng)",
    year: 2025,
    note: "Framework-agnostic course on reflection, tool use, planning and multi-agent patterns, with unusual emphasis on evals and error analysis.",
    essential: true,
  },
  aiEngineeringBook: {
    title: "AI Engineering",
    url: "https://www.oreilly.com/library/view/ai-engineering/9781098166298/",
    kind: "book",
    source: "Chip Huyen (O'Reilly)",
    year: 2025,
    note: "The best book on building with foundation models: evaluation, prompting, RAG, agents, fine-tuning, dataset engineering and inference.",
    essential: true,
    paid: true,
  },
  karpathyDeepDive: {
    title: "Deep Dive into LLMs like ChatGPT",
    url: "https://www.youtube.com/watch?v=7xTGNNLPyMI",
    kind: "video",
    source: "Andrej Karpathy",
    year: 2025,
    note: "Pretraining to SFT to RL and reasoning in one sitting — the most accurate mental model of the thing you're orchestrating.",
    essential: true,
  },

  // ── Guides: Anthropic engineering ─────────────────────────────────────────
  writingTools: {
    title: "Writing Effective Tools for Agents — with Agents",
    url: "https://www.anthropic.com/engineering/writing-tools-for-agents",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "Choosing, namespacing and describing tools, token-efficient responses, and letting agents evaluate and rewrite their own tools.",
  },
  multiAgentResearch: {
    title: "How We Built Our Multi-Agent Research System",
    url: "https://www.anthropic.com/engineering/multi-agent-research-system",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "An orchestrator–worker system in production: delegation prompts, effort scaling, evals — and why it burns roughly 15× the tokens of chat.",
  },
  contextualRetrieval: {
    title: "Introducing Contextual Retrieval",
    url: "https://www.anthropic.com/engineering/contextual-retrieval",
    kind: "guide",
    source: "Anthropic",
    year: 2024,
    note: "Prepend LLM-written context to each chunk before embedding and BM25 indexing — with measured drops in retrieval failure.",
  },
  thinkTool: {
    title: "The “think” Tool",
    url: "https://www.anthropic.com/engineering/claude-think-tool",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "A no-op tool that gives the model a place to reason between tool calls, and where it measurably helps policy-heavy tasks.",
  },
  codeExecutionMcp: {
    title: "Code Execution with MCP",
    url: "https://www.anthropic.com/engineering/code-execution-with-mcp",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "Expose MCP servers as code APIs so the agent loads only the tools it needs and keeps bulky intermediate data out of context.",
  },
  advancedToolUse: {
    title: "Introducing Advanced Tool Use",
    url: "https://www.anthropic.com/engineering/advanced-tool-use",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "Tool search, programmatic tool calling and tool-use examples — techniques for agents that need hundreds of tools.",
  },
  longRunningHarness: {
    title: "Effective Harnesses for Long-Running Agents",
    url: "https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "An initializer agent plus incremental workers, progress files and feature lists: keeping an agent productive across many context windows.",
  },
  harnessDesign: {
    title: "Harness Design for Long-Running Application Development",
    url: "https://www.anthropic.com/engineering/harness-design-long-running-apps",
    kind: "guide",
    source: "Anthropic",
    year: 2026,
    note: "Planner, generator and evaluator agents with negotiated “sprint contracts” — and the rule to strip harness parts as models improve.",
  },
  managedAgents: {
    title: "Scaling Managed Agents: Decoupling the Brain from the Hands",
    url: "https://www.anthropic.com/engineering/managed-agents",
    kind: "guide",
    source: "Anthropic",
    year: 2026,
    note: "A stateless harness, sandboxes called as tools, and a durable append-only session log — an agent architecture built to survive failures.",
  },
  agentSkills: {
    title: "Equipping Agents for the Real World with Agent Skills",
    url: "https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "Package procedural knowledge as folders of instructions and scripts that load progressively — versionable procedural memory.",
  },
  sweBenchSonnet: {
    title: "Raising the Bar on SWE-bench Verified",
    url: "https://www.anthropic.com/engineering/swe-bench-sonnet",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "A deliberately minimal coding-agent scaffold, and the tool-design details — like requiring absolute paths — that moved the score.",
  },
  claudeCodeBestPractices: {
    title: "Best Practices for Claude Code",
    url: "https://code.claude.com/docs/en/best-practices",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "Explore → plan → code → verify, project memory files and tight feedback loops — habits that transfer to any coding agent.",
  },
  claudeCodeSandboxing: {
    title: "Making Claude Code More Secure and Autonomous with Sandboxing",
    url: "https://www.anthropic.com/engineering/claude-code-sandboxing",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "Filesystem and network isolation as the answer to approval fatigue: fewer prompts and a smaller blast radius.",
  },
  autoMode: {
    title: "How We Built Claude Code Auto Mode",
    url: "https://www.anthropic.com/engineering/claude-code-auto-mode",
    kind: "guide",
    source: "Anthropic",
    year: 2026,
    note: "Permission tiers plus a transcript classifier that blocks risky actions — with published false-positive and false-negative rates.",
  },
  infraNoise: {
    title: "Quantifying Infrastructure Noise in Agentic Coding Evals",
    url: "https://www.anthropic.com/engineering/infrastructure-noise",
    kind: "guide",
    source: "Anthropic",
    year: 2026,
    note: "Resource limits alone moved Terminal-Bench 2.0 scores by up to 6 points — read before trusting a small leaderboard gap.",
  },
  evalAwareness: {
    title: "Eval Awareness in Claude Opus 4.6's BrowseComp Performance",
    url: "https://www.anthropic.com/engineering/eval-awareness-browsecomp",
    kind: "guide",
    source: "Anthropic",
    year: 2026,
    note: "A model inferred it was being benchmarked, found the answer key and decrypted it — a case study in why static web benchmarks decay.",
  },
  mcpDonation: {
    title: "Donating MCP to the Agentic AI Foundation",
    url: "https://www.anthropic.com/news/donating-the-model-context-protocol-and-establishing-of-the-agentic-ai-foundation",
    kind: "guide",
    source: "Anthropic",
    year: 2025,
    note: "MCP moves to a Linux Foundation fund co-founded with Block and OpenAI, alongside goose and AGENTS.md — vendor-neutral governance.",
  },
  barryZhangTalk: {
    title: "How We Build Effective Agents",
    url: "https://www.youtube.com/watch?v=D7_ipDqhtwk",
    kind: "video",
    source: "Barry Zhang (Anthropic)",
    year: 2025,
    note: "A short talk distilling the guide: don't build agents for everything, keep them simple, and think like your agent.",
  },

  // ── Guides: practitioners and other labs ──────────────────────────────────
  openaiHarnessEngineering: {
    title: "Harness Engineering: Leveraging Codex in an Agent-First World",
    url: "https://openai.com/index/harness-engineering/",
    kind: "guide",
    source: "OpenAI (Ryan Lopopolo)",
    year: 2026,
    note: "Five months shipping a product with no hand-written code: engineers design environments, specify intent and build feedback loops.",
  },
  googleAgentsWhitepaper: {
    title: "Agents (whitepaper)",
    url: "https://www.kaggle.com/whitepaper-agents",
    kind: "guide",
    source: "Google",
    year: 2024,
    note: "The model–tools–orchestration architecture, extensions vs functions vs data stores, and the reasoning frameworks behind agents.",
  },
  cognitionMultiAgent: {
    title: "Don't Build Multi-Agents",
    url: "https://cognition.com/blog/dont-build-multi-agents",
    kind: "guide",
    source: "Cognition (Walden Yan)",
    year: 2025,
    note: "The strongest case against naive multi-agent designs: share full context, because every action carries implicit decisions.",
  },
  langchainFrameworks: {
    title: "How to Think About Agent Frameworks",
    url: "https://www.langchain.com/blog/how-to-think-about-agent-frameworks",
    kind: "guide",
    source: "LangChain (Harrison Chase)",
    year: 2025,
    note: "Separates agent abstractions from orchestration, and names what a framework must earn its keep with: persistence, streaming, human-in-the-loop.",
  },
  langchainContextEng: {
    title: "Context Engineering for Agents",
    url: "https://www.langchain.com/blog/context-engineering-for-agents",
    kind: "guide",
    source: "LangChain (Lance Martin)",
    year: 2025,
    note: "The write / select / compress / isolate taxonomy for deciding what reaches the context window.",
  },
  manusContext: {
    title: "Context Engineering for AI Agents: Lessons from Building Manus",
    url: "https://manus.im/blog/Context-Engineering-for-AI-Agents-Lessons-from-Building-Manus",
    kind: "guide",
    source: "Manus (Yichao “Peak” Ji)",
    year: 2025,
    note: "Production lessons: design around the KV cache, mask tools instead of removing them, use files as memory, keep errors in context.",
  },
  twelveFactor: {
    title: "12-Factor Agents",
    url: "https://github.com/humanlayer/12-factor-agents",
    kind: "repo",
    source: "HumanLayer (Dex Horthy)",
    year: 2025,
    note: "Principles for production agents: own your prompts, own your context window, own your control flow, keep agents small and focused.",
  },
  willisonTrifecta: {
    title: "The Lethal Trifecta for AI Agents",
    url: "https://simonwillison.net/2025/Jun/16/the-lethal-trifecta/",
    kind: "guide",
    source: "Simon Willison",
    year: 2025,
    note: "Private data + untrusted content + a way to communicate out = exfiltration. The clearest mental model in agent security.",
  },
  willisonAgentDefinition: {
    title: "I Think “Agent” May Finally Have a Widely Enough Agreed Upon Definition to Be Useful Jargon Now",
    url: "https://simonwillison.net/2025/Sep/18/agents/",
    kind: "guide",
    source: "Simon Willison",
    year: 2025,
    note: "“An LLM agent runs tools in a loop to achieve a goal” — the working definition, and why the vaguer ones fail.",
  },
  hamelEvals: {
    title: "Your AI Product Needs Evals",
    url: "https://hamel.dev/blog/posts/evals/",
    kind: "guide",
    source: "Hamel Husain",
    year: 2024,
    note: "Why evals are the engine of iteration, organized as unit tests, human and model review, and A/B tests.",
  },
  hamelFieldGuide: {
    title: "A Field Guide to Rapidly Improving AI Products",
    url: "https://hamel.dev/blog/posts/field-guide/",
    kind: "guide",
    source: "Hamel Husain",
    year: 2025,
    note: "Error analysis first: read your traces, build a simple data viewer, and let observed failure modes set the roadmap.",
  },
  hamelEvalsFaq: {
    title: "AI Evals: Everything You Need to Know",
    url: "https://hamel.dev/blog/posts/evals-faq/",
    kind: "guide",
    source: "Hamel Husain & Shreya Shankar",
    year: 2025,
    note: "Straight answers on binary vs Likert judges, how many examples you need, validating judges, and evaluating RAG and agents.",
  },
  eugeneYanPatterns: {
    title: "Patterns for Building LLM-based Systems & Products",
    url: "https://eugeneyan.com/writing/llm-patterns/",
    kind: "guide",
    source: "Eugene Yan",
    year: 2023,
    note: "Evals, RAG, fine-tuning, caching, guardrails, defensive UX and feedback loops — still the right checklist.",
  },
  appliedLlms: {
    title: "What We’ve Learned From A Year of Building with LLMs",
    url: "https://applied-llms.org/",
    kind: "guide",
    source: "Yan, Bischof, Frye, Husain, Liu & Shankar",
    year: 2024,
    note: "Tactical, operational and strategic lessons from six practitioners — the most-cited field report on shipping LLM products.",
  },
  eugeneYanJudges: {
    title: "Evaluating the Effectiveness of LLM-Evaluators (aka LLM-as-Judge)",
    url: "https://eugeneyan.com/writing/llm-evaluators/",
    kind: "guide",
    source: "Eugene Yan",
    year: 2024,
    note: "A survey of LLM-as-judge research: when judges agree with humans, which biases matter, and how to set them up.",
  },
  huyenGenAIPlatform: {
    title: "Building A Generative AI Platform",
    url: "https://huyenchip.com/2024/07/25/genai-platform.html",
    kind: "guide",
    source: "Chip Huyen",
    year: 2024,
    note: "A production architecture built up one component at a time: context construction, guardrails, routers, caches, agents, observability.",
  },
  wengHallucination: {
    title: "Extrinsic Hallucinations in LLMs",
    url: "https://lilianweng.github.io/posts/2024-07-07-hallucination/",
    kind: "guide",
    source: "Lilian Weng",
    year: 2024,
    note: "Causes, detection methods and mitigation techniques, each tied to the research behind it.",
  },
  wengPrompting: {
    title: "Prompt Engineering",
    url: "https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/",
    kind: "guide",
    source: "Lilian Weng",
    year: 2023,
    note: "A research-grounded tour of prompting: example selection, chain-of-thought variants, self-consistency, tool-augmented prompting.",
  },
  wengThinking: {
    title: "Why We Think",
    url: "https://lilianweng.github.io/posts/2025-05-01-thinking/",
    kind: "guide",
    source: "Lilian Weng",
    year: 2025,
    note: "Test-time compute: chain-of-thought, parallel vs sequential sampling, RL for reasoning, and whether the thoughts are faithful.",
  },
  raschkaReasoning: {
    title: "Understanding Reasoning LLMs",
    url: "https://magazine.sebastianraschka.com/p/understanding-reasoning-llms",
    kind: "guide",
    source: "Sebastian Raschka",
    year: 2025,
    note: "Four routes to reasoning models — inference-time scaling, pure RL, SFT plus RL, distillation — explained through DeepSeek-R1.",
  },
  chromaContextRot: {
    title: "Context Rot: How Increasing Input Tokens Impacts LLM Performance",
    url: "https://www.trychroma.com/research/context-rot",
    kind: "guide",
    source: "Chroma Research",
    year: 2025,
    note: "Performance degrades as inputs grow, even on simple tasks — the empirical case for curating context instead of filling it.",
  },
  ngAgenticPatterns: {
    title: "Four AI Agent Strategies That Improve GPT-4 and GPT-3.5 Performance",
    url: "https://www.deeplearning.ai/the-batch/how-agents-can-improve-llm-performance",
    kind: "guide",
    source: "Andrew Ng (The Batch)",
    year: 2024,
    note: "The letter that popularized “agentic workflows” and the reflection / tool use / planning / multi-agent framing.",
  },
  promptingGuide: {
    title: "Prompt Engineering Guide",
    url: "https://www.promptingguide.ai/",
    kind: "guide",
    source: "DAIR.AI",
    note: "A broad, regularly updated reference on prompting techniques, agents and RAG, with links to the underlying papers.",
  },

  // ── Papers ────────────────────────────────────────────────────────────────
  cotPaper: {
    title: "Chain-of-Thought Prompting Elicits Reasoning in Large Language Models",
    url: "https://arxiv.org/abs/2201.11903",
    kind: "paper",
    source: "Wei et al.",
    year: 2022,
    note: "Worked reasoning steps in the prompt unlock multi-step reasoning at scale — the paper that started it.",
  },
  zeroShotCot: {
    title: "Large Language Models are Zero-Shot Reasoners",
    url: "https://arxiv.org/abs/2205.11916",
    kind: "paper",
    source: "Kojima et al.",
    year: 2022,
    note: "The “Let's think step by step” paper: chain-of-thought without any worked examples.",
  },
  selfConsistency: {
    title: "Self-Consistency Improves Chain of Thought Reasoning in Language Models",
    url: "https://arxiv.org/abs/2203.11171",
    kind: "paper",
    source: "Wang et al.",
    year: 2022,
    note: "Sample several reasoning paths and take the majority answer — the simplest test-time-compute trick that reliably helps.",
  },
  totPaper: {
    title: "Tree of Thoughts: Deliberate Problem Solving with Large Language Models",
    url: "https://arxiv.org/abs/2305.10601",
    kind: "paper",
    source: "Yao et al.",
    year: 2023,
    note: "Search over intermediate thoughts with self-evaluation and backtracking — powerful, expensive and instructive.",
  },
  toolformer: {
    title: "Toolformer: Language Models Can Teach Themselves to Use Tools",
    url: "https://arxiv.org/abs/2302.04761",
    kind: "paper",
    source: "Schick et al.",
    year: 2023,
    note: "A model teaches itself when and how to call APIs — the self-supervised origin story of tool use.",
  },
  reflexion: {
    title: "Reflexion: Language Agents with Verbal Reinforcement Learning",
    url: "https://arxiv.org/abs/2303.11366",
    kind: "paper",
    source: "Shinn et al.",
    year: 2023,
    note: "Agents write lessons from failed attempts into memory and retry — learning from feedback without weight updates.",
  },
  selfRefine: {
    title: "Self-Refine: Iterative Refinement with Self-Feedback",
    url: "https://arxiv.org/abs/2303.17651",
    kind: "paper",
    source: "Madaan et al.",
    year: 2023,
    note: "Generate, critique, refine with a single model — the baseline evaluator–optimizer loop.",
  },
  cannotSelfCorrect: {
    title: "Large Language Models Cannot Self-Correct Reasoning Yet",
    url: "https://arxiv.org/abs/2310.01798",
    kind: "paper",
    source: "Huang et al.",
    year: 2023,
    note: "The necessary counterweight: without external feedback, self-correction often fails to help and can make answers worse.",
  },
  rewoo: {
    title: "ReWOO: Decoupling Reasoning from Observations for Efficient Augmented Language Models",
    url: "https://arxiv.org/abs/2305.18323",
    kind: "paper",
    source: "Xu et al.",
    year: 2023,
    note: "Plan every tool call up front with placeholders, then execute — far fewer tokens than step-by-step ReAct.",
  },
  llmCompiler: {
    title: "An LLM Compiler for Parallel Function Calling",
    url: "https://arxiv.org/abs/2312.04511",
    kind: "paper",
    source: "Kim et al.",
    year: 2023,
    note: "Plans tool calls as a dependency graph and runs the independent ones in parallel.",
  },
  generativeAgents: {
    title: "Generative Agents: Interactive Simulacra of Human Behavior",
    url: "https://arxiv.org/abs/2304.03442",
    kind: "paper",
    source: "Park et al.",
    year: 2023,
    note: "The memory stream: retrieval scored by recency, importance and relevance, plus reflection into higher-level memories.",
  },
  memgpt: {
    title: "MemGPT: Towards LLMs as Operating Systems",
    url: "https://arxiv.org/abs/2310.08560",
    kind: "paper",
    source: "Packer et al.",
    year: 2023,
    note: "Virtual context management: the model pages information between its window and external storage through function calls.",
  },
  coala: {
    title: "Cognitive Architectures for Language Agents",
    url: "https://arxiv.org/abs/2309.02427",
    kind: "paper",
    source: "Sumers et al.",
    year: 2023,
    note: "The working / episodic / semantic / procedural memory taxonomy that most agent-memory writing now borrows.",
  },
  voyager: {
    title: "Voyager: An Open-Ended Embodied Agent with Large Language Models",
    url: "https://arxiv.org/abs/2305.16291",
    kind: "paper",
    source: "Wang et al.",
    year: 2023,
    note: "A Minecraft agent that grows a library of reusable code skills — procedural memory made concrete.",
  },
  sweAgent: {
    title: "SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering",
    url: "https://arxiv.org/abs/2405.15793",
    kind: "paper",
    source: "Yang et al.",
    year: 2024,
    note: "Coined the agent–computer interface: purpose-built commands and feedback formats beat raw shell access.",
  },
  codeAct: {
    title: "Executable Code Actions Elicit Better LLM Agents",
    url: "https://arxiv.org/abs/2402.01030",
    kind: "paper",
    source: "Wang et al.",
    year: 2024,
    note: "Python code as the action space instead of JSON tool calls: composable, stateful and measurably more successful.",
  },
  ragPaper: {
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    url: "https://arxiv.org/abs/2005.11401",
    kind: "paper",
    source: "Lewis et al.",
    year: 2020,
    note: "The paper that named RAG: a retriever and a generator trained to work together.",
  },
  lostInMiddle: {
    title: "Lost in the Middle: How Language Models Use Long Contexts",
    url: "https://arxiv.org/abs/2307.03172",
    kind: "paper",
    source: "Liu et al.",
    year: 2023,
    note: "Accuracy is highest when the relevant passage sits at the start or end of the context, and sags in the middle.",
  },
  hyde: {
    title: "Precise Zero-Shot Dense Retrieval without Relevance Labels (HyDE)",
    url: "https://arxiv.org/abs/2212.10496",
    kind: "paper",
    source: "Gao et al.",
    year: 2022,
    note: "Embed a hypothetical answer instead of the question to retrieve better matches.",
  },
  selfRag: {
    title: "Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection",
    url: "https://arxiv.org/abs/2310.11511",
    kind: "paper",
    source: "Asai et al.",
    year: 2023,
    note: "A model trained to decide when to retrieve and to critique its own use of what it retrieved.",
  },
  crag: {
    title: "Corrective Retrieval Augmented Generation",
    url: "https://arxiv.org/abs/2401.15884",
    kind: "paper",
    source: "Yan et al.",
    year: 2024,
    note: "Grade retrieved documents and fall back to web search when they're weak — the corrective-RAG pattern.",
  },
  graphRag: {
    title: "From Local to Global: A Graph RAG Approach to Query-Focused Summarization",
    url: "https://arxiv.org/abs/2404.16130",
    kind: "paper",
    source: "Edge et al. (Microsoft)",
    year: 2024,
    note: "Entity graphs plus community summaries for corpus-wide “sensemaking” questions that chunk retrieval can't answer.",
  },
  hnsw: {
    title: "Efficient and Robust Approximate Nearest Neighbor Search Using HNSW Graphs",
    url: "https://arxiv.org/abs/1603.09320",
    kind: "paper",
    source: "Malkov & Yashunin",
    year: 2016,
    note: "The graph index behind most vector databases — worth understanding for its recall, latency and memory knobs.",
  },
  tauBench: {
    title: "τ-bench: A Benchmark for Tool-Agent-User Interaction in Real-World Domains",
    url: "https://arxiv.org/abs/2406.12045",
    kind: "paper",
    source: "Yao et al. (Sierra)",
    year: 2024,
    note: "Simulated users, policies and tools for customer-service agents — and the pass^k reliability metric.",
  },
  tau2Bench: {
    title: "τ²-Bench: Evaluating Conversational Agents in a Dual-Control Environment",
    url: "https://arxiv.org/abs/2506.07982",
    kind: "paper",
    source: "Barres et al. (Sierra)",
    year: 2025,
    note: "Extends τ-bench to settings where the user also acts on the environment, as in technical support.",
  },
  sweBench: {
    title: "SWE-bench: Can Language Models Resolve Real-World GitHub Issues?",
    url: "https://arxiv.org/abs/2310.06770",
    kind: "paper",
    source: "Jimenez et al.",
    year: 2023,
    note: "Real GitHub issues graded by each repository's own tests — the reference benchmark for coding agents.",
  },
  gaia: {
    title: "GAIA: A Benchmark for General AI Assistants",
    url: "https://arxiv.org/abs/2311.12983",
    kind: "paper",
    source: "Mialon et al.",
    year: 2023,
    note: "Questions that are simple for people but need browsing, tools and multi-step reasoning for agents.",
  },
  webArena: {
    title: "WebArena: A Realistic Web Environment for Building Autonomous Agents",
    url: "https://arxiv.org/abs/2307.13854",
    kind: "paper",
    source: "Zhou et al.",
    year: 2023,
    note: "Self-hosted replicas of real websites with functional, outcome-based grading of web tasks.",
  },
  osWorld: {
    title: "OSWorld: Benchmarking Multimodal Agents for Open-Ended Tasks in Real Computer Environments",
    url: "https://arxiv.org/abs/2404.07972",
    kind: "paper",
    source: "Xie et al.",
    year: 2024,
    note: "Real desktop tasks across applications — the main yardstick for computer-use agents.",
  },
  browseComp: {
    title: "BrowseComp: A Simple Yet Challenging Benchmark for Browsing Agents",
    url: "https://arxiv.org/abs/2504.12516",
    kind: "paper",
    source: "Wei et al. (OpenAI)",
    year: 2025,
    note: "1,266 hard-to-find but easy-to-verify questions that test persistent, creative web search.",
  },
  agentsThatMatter: {
    title: "AI Agents That Matter",
    url: "https://arxiv.org/abs/2407.01502",
    kind: "paper",
    source: "Kapoor et al.",
    year: 2024,
    note: "Benchmarks that ignore cost reward needless complexity — report accuracy and cost together, and beware overfitting.",
  },
  metrTimeHorizons: {
    title: "Measuring AI Ability to Complete Long Tasks",
    url: "https://metr.org/blog/2025-03-19-measuring-ai-ability-to-complete-long-tasks/",
    kind: "paper",
    source: "METR",
    year: 2025,
    note: "The time-horizon metric: the length of task frontier agents complete at 50% reliability has doubled roughly every seven months.",
  },
  llmJudge: {
    title: "Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena",
    url: "https://arxiv.org/abs/2306.05685",
    kind: "paper",
    source: "Zheng et al.",
    year: 2023,
    note: "The study that legitimized LLM judges and catalogued their position, verbosity and self-enhancement biases.",
  },
  indirectInjection: {
    title: "Not What You've Signed Up For: Compromising Real-World LLM-Integrated Applications with Indirect Prompt Injection",
    url: "https://arxiv.org/abs/2302.12173",
    kind: "paper",
    source: "Greshake et al.",
    year: 2023,
    note: "Defined indirect prompt injection: instructions planted in content the model reads, not typed by the user.",
  },
  camel: {
    title: "Defeating Prompt Injections by Design (CaMeL)",
    url: "https://arxiv.org/abs/2503.18813",
    kind: "paper",
    source: "Debenedetti et al.",
    year: 2025,
    note: "A privileged planner, a quarantined parser and capability tracking, so untrusted data can never steer control flow.",
  },
  injectionPatterns: {
    title: "Design Patterns for Securing LLM Agents against Prompt Injections",
    url: "https://arxiv.org/abs/2506.08837",
    kind: "paper",
    source: "Beurer-Kellner et al.",
    year: 2025,
    note: "Six patterns — action-selector, plan-then-execute, dual LLM and more — that trade agent flexibility for real injection resistance.",
  },
  multiAgentFail: {
    title: "Why Do Multi-Agent LLM Systems Fail?",
    url: "https://arxiv.org/abs/2503.13657",
    kind: "paper",
    source: "Cemri et al.",
    year: 2025,
    note: "A failure taxonomy built from annotated traces: specification problems, inter-agent misalignment and weak task verification.",
  },
  whyHallucinate: {
    title: "Why Language Models Hallucinate",
    url: "https://arxiv.org/abs/2509.04664",
    kind: "paper",
    source: "Kalai et al. (OpenAI)",
    year: 2025,
    note: "Hallucination as a predictable result of training and of benchmarks that reward a confident guess over “I don't know”.",
  },
  chainOfVerification: {
    title: "Chain-of-Verification Reduces Hallucination in Large Language Models",
    url: "https://arxiv.org/abs/2309.11495",
    kind: "paper",
    source: "Dhuliawala et al.",
    year: 2023,
    note: "Draft, plan verification questions, answer them independently, then revise — a cheap factuality boost.",
  },
  reasoningNotSay: {
    title: "Reasoning Models Don't Always Say What They Think",
    url: "https://www.anthropic.com/research/reasoning-models-dont-say-think",
    kind: "paper",
    source: "Anthropic",
    year: 2025,
    note: "Evidence that chain-of-thought often omits what actually drove an answer — required reading before using it as a monitor.",
  },
  instructGpt: {
    title: "Training Language Models to Follow Instructions with Human Feedback",
    url: "https://arxiv.org/abs/2203.02155",
    kind: "paper",
    source: "Ouyang et al. (OpenAI)",
    year: 2022,
    note: "The SFT → reward model → PPO recipe that turned base models into assistants.",
  },
  dpo: {
    title: "Direct Preference Optimization: Your Language Model is Secretly a Reward Model",
    url: "https://arxiv.org/abs/2305.18290",
    kind: "paper",
    source: "Rafailov et al.",
    year: 2023,
    note: "Preference tuning without a separate reward model or RL loop — a classification-style loss on chosen vs rejected pairs.",
  },
  deepseekMath: {
    title: "DeepSeekMath: Pushing the Limits of Mathematical Reasoning in Open Language Models",
    url: "https://arxiv.org/abs/2402.03300",
    kind: "paper",
    source: "Shao et al.",
    year: 2024,
    note: "Introduced GRPO, the critic-free RL algorithm behind many open reasoning models.",
  },
  deepseekR1: {
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning",
    url: "https://arxiv.org/abs/2501.12948",
    kind: "paper",
    source: "DeepSeek-AI",
    year: 2025,
    note: "Reasoning from large-scale RL with verifiable rewards, plus distillation into small models — the open recipe.",
  },
  lora: {
    title: "LoRA: Low-Rank Adaptation of Large Language Models",
    url: "https://arxiv.org/abs/2106.09685",
    kind: "paper",
    source: "Hu et al.",
    year: 2021,
    note: "Train low-rank update matrices beside frozen weights: a sliver of the parameters, swappable adapters.",
  },
  qlora: {
    title: "QLoRA: Efficient Finetuning of Quantized LLMs",
    url: "https://arxiv.org/abs/2305.14314",
    kind: "paper",
    source: "Dettmers et al.",
    year: 2023,
    note: "LoRA over a 4-bit quantized base model — what made fine-tuning large models possible on a single GPU.",
  },
  gorilla: {
    title: "Gorilla: Large Language Model Connected with Massive APIs",
    url: "https://arxiv.org/abs/2305.15334",
    kind: "paper",
    source: "Patil et al.",
    year: 2023,
    note: "Fine-tuning for accurate API calls with retrieval over documentation — and the origin of the Berkeley leaderboard.",
  },
  toolLlm: {
    title: "ToolLLM: Facilitating Large Language Models to Master 16000+ Real-world APIs",
    url: "https://arxiv.org/abs/2307.16789",
    kind: "paper",
    source: "Qin et al.",
    year: 2023,
    note: "ToolBench: real APIs at scale and a recipe for building tool-use training data from them.",
  },
  apiGen: {
    title: "APIGen: Automated Pipeline for Generating Verifiable and Diverse Function-Calling Datasets",
    url: "https://arxiv.org/abs/2406.18518",
    kind: "paper",
    source: "Liu et al. (Salesforce)",
    year: 2024,
    note: "Synthetic function-calling data with format, execution and semantic verification — the method behind the xLAM datasets.",
  },
  promptReport: {
    title: "The Prompt Report: A Systematic Survey of Prompt Engineering Techniques",
    url: "https://arxiv.org/abs/2406.06608",
    kind: "paper",
    source: "Schulhoff et al.",
    year: 2024,
    note: "A taxonomy of prompting techniques with a shared vocabulary — useful as a map, not a recipe book.",
  },
  pagedAttention: {
    title: "Efficient Memory Management for Large Language Model Serving with PagedAttention",
    url: "https://arxiv.org/abs/2309.06180",
    kind: "paper",
    source: "Kwon et al.",
    year: 2023,
    note: "The vLLM paper: the KV cache paged like virtual memory, enabling far higher serving throughput.",
  },
  slmAgents: {
    title: "Small Language Models are the Future of Agentic AI",
    url: "https://arxiv.org/abs/2506.02153",
    kind: "paper",
    source: "Belcak et al. (NVIDIA)",
    year: 2025,
    note: "Most agent subtasks are narrow enough for small models — the argument, and a recipe for migrating to them.",
  },

  // ── Courses ───────────────────────────────────────────────────────────────
  kaggleAgentsIntensive: {
    title: "5-Day AI Agents Intensive",
    url: "https://www.kaggle.com/learn-guide/5-day-agents",
    kind: "course",
    source: "Google & Kaggle",
    year: 2025,
    note: "The self-paced version of Google's agents course — a whitepaper plus codelabs each day, built on Gemini and ADK.",
  },
  berkeleyLlmAgents: {
    title: "Large Language Model Agents (MOOC)",
    url: "https://llmagents-learning.org/f24",
    kind: "course",
    source: "UC Berkeley",
    year: 2024,
    note: "Lectures from the researchers behind many of the papers in this library — the best research-level overview of agents.",
  },
  berkeleyAdvancedAgents: {
    title: "Advanced Large Language Model Agents (MOOC)",
    url: "https://llmagents-learning.org/sp25",
    kind: "course",
    source: "UC Berkeley",
    year: 2025,
    note: "The follow-on: reasoning, planning, code and web agents, and agent safety, at research depth.",
  },
  berkeleyAgenticAI: {
    title: "Agentic AI (MOOC)",
    url: "https://agenticai-learning.org/f25",
    kind: "course",
    source: "UC Berkeley",
    year: 2025,
    note: "The Fall 2025 edition, building on the two earlier MOOCs, with guest lectures from industry and research labs.",
  },
  dlaiLangGraph: {
    title: "AI Agents in LangGraph",
    url: "https://www.deeplearning.ai/courses/ai-agents-in-langgraph",
    kind: "course",
    source: "DeepLearning.AI × LangChain",
    year: 2024,
    note: "Build an agent from scratch, then rebuild it in LangGraph with persistence, streaming and human-in-the-loop.",
  },
  dlaiMcp: {
    title: "MCP: Build Rich-Context AI Apps with Anthropic",
    url: "https://www.deeplearning.ai/courses/mcp-build-rich-context-ai-apps-with-anthropic",
    kind: "course",
    source: "DeepLearning.AI × Anthropic",
    year: 2025,
    note: "Build MCP servers and clients in Python, then connect them to a chatbot and to existing MCP hosts.",
  },
  dlaiEvaluatingAgents: {
    title: "Evaluating AI Agents",
    url: "https://www.deeplearning.ai/courses/evaluating-ai-agents",
    kind: "course",
    source: "DeepLearning.AI × Arize",
    year: 2025,
    note: "Instrument an agent with traces, evaluate its router, skills and trajectory, and run structured experiments.",
  },
  dlaiAgentMemory: {
    title: "Long-Term Agentic Memory with LangGraph",
    url: "https://www.deeplearning.ai/courses/long-term-agentic-memory-with-langgraph",
    kind: "course",
    source: "DeepLearning.AI × LangChain",
    year: 2025,
    note: "Semantic, episodic and procedural memory implemented inside an email-assistant agent.",
  },
  langchainAcademy: {
    title: "Introduction to LangGraph",
    url: "https://academy.langchain.com/courses/intro-to-langgraph",
    kind: "course",
    source: "LangChain Academy",
    note: "The free official course: state, memory, human-in-the-loop, subgraphs and deployment.",
  },
  claudeAcademy: {
    title: "Claude Academy",
    url: "https://academy.claude.com/",
    kind: "course",
    source: "Anthropic",
    note: "Anthropic's free courses on building with the Claude API, MCP and agents.",
  },
  promptEngTutorial: {
    title: "Prompt Engineering Interactive Tutorial",
    url: "https://github.com/anthropics/prompt-eng-interactive-tutorial",
    kind: "course",
    source: "Anthropic",
    year: 2024,
    note: "Nine hands-on chapters with exercises — the fastest way to build real prompting skill.",
  },
  anthropicCourses: {
    title: "Anthropic Courses",
    url: "https://github.com/anthropics/courses",
    kind: "course",
    source: "Anthropic",
    year: 2024,
    note: "Notebook courses on API fundamentals, real-world prompting, prompt evaluations and tool use.",
  },
  hfLlmCourse: {
    title: "LLM Course",
    url: "https://huggingface.co/learn/llm-course/chapter1/1",
    kind: "course",
    source: "Hugging Face",
    year: 2025,
    note: "Transformers, tokenizers, fine-tuning and reasoning models with the Hugging Face stack — free.",
  },
  stanfordCs336: {
    title: "CS336: Language Modeling from Scratch",
    url: "https://cs336.stanford.edu/",
    kind: "course",
    source: "Stanford",
    year: 2025,
    note: "Build every piece of a language model yourself — tokenizer, transformer, training, scaling, alignment. Demanding and superb.",
  },
  msAgentsBeginners: {
    title: "AI Agents for Beginners",
    url: "https://github.com/microsoft/ai-agents-for-beginners",
    kind: "course",
    source: "Microsoft",
    year: 2025,
    note: "18 lessons with code covering agent patterns, tool use, agentic RAG, multi-agent design and production.",
  },
  mavenEvals: {
    title: "AI Evals for Engineers & PMs",
    url: "https://maven.com/parlance-labs/evals",
    kind: "course",
    source: "Hamel Husain & Shreya Shankar",
    year: 2025,
    note: "The most thorough course on evals: error analysis, LLM judges, RAG and agent evaluation, evals in CI.",
    paid: true,
  },

  // ── Videos ────────────────────────────────────────────────────────────────
  karpathyIntro: {
    title: "[1hr Talk] Intro to Large Language Models",
    url: "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    kind: "video",
    source: "Andrej Karpathy",
    year: 2023,
    note: "The one-hour version: what an LLM is, how it's trained, where it's heading, and its security problems.",
  },
  karpathyGpt: {
    title: "Let's Build GPT: From Scratch, in Code, Spelled Out",
    url: "https://www.youtube.com/watch?v=kCc8FmEb1nY",
    kind: "video",
    source: "Andrej Karpathy",
    year: 2023,
    note: "Write a transformer from an empty file — the best way to make attention concrete.",
  },
  karpathyTokenizer: {
    title: "Let's Build the GPT Tokenizer",
    url: "https://www.youtube.com/watch?v=zduSFxRajkE",
    kind: "video",
    source: "Andrej Karpathy",
    year: 2024,
    note: "Why so many LLM quirks — arithmetic, spelling, the cost of non-English text — trace back to tokenization.",
  },
  karpathySoftware3: {
    title: "Software Is Changing (Again)",
    url: "https://www.youtube.com/watch?v=LCEmiRjPEtQ",
    kind: "video",
    source: "Andrej Karpathy",
    year: 2025,
    note: "Software 3.0: LLMs as a new kind of computer, partial-autonomy products, and building for agents as users.",
  },
  threeBlueGpt: {
    title: "Transformers, the Tech Behind LLMs",
    url: "https://www.youtube.com/watch?v=wjZofJX0v4M",
    kind: "video",
    source: "3Blue1Brown",
    year: 2024,
    note: "The clearest visual explanation of what actually happens inside a transformer.",
  },

  // ── Books ─────────────────────────────────────────────────────────────────
  buildingAgentsBook: {
    title: "Building Applications with AI Agents",
    url: "https://www.oreilly.com/library/view/building-applications-with/9781098176495/",
    kind: "book",
    source: "Michael Albada (O'Reilly)",
    year: 2025,
    note: "Designing single- and multi-agent systems: tools, memory, orchestration, evaluation and deployment trade-offs.",
    paid: true,
  },
  raschkaBook: {
    title: "Build a Large Language Model (From Scratch)",
    url: "https://www.manning.com/books/build-a-large-language-model-from-scratch",
    kind: "book",
    source: "Sebastian Raschka (Manning)",
    year: 2024,
    note: "Code a GPT-style model end to end in PyTorch, then pretrain and fine-tune it. The free companion repo is excellent too.",
    paid: true,
  },
  handsOnLlm: {
    title: "Hands-On Large Language Models",
    url: "https://www.oreilly.com/library/view/hands-on-large-language/9781098150952/",
    kind: "book",
    source: "Jay Alammar & Maarten Grootendorst (O'Reilly)",
    year: 2024,
    note: "Highly visual, practical coverage of embeddings, retrieval, prompting and fine-tuning.",
    paid: true,
  },
  promptEngForLlms: {
    title: "Prompt Engineering for LLMs",
    url: "https://www.oreilly.com/library/view/prompt-engineering-for/9781098156145/",
    kind: "book",
    source: "John Berryman & Albert Ziegler (O'Reilly)",
    year: 2024,
    note: "Prompting treated as engineering, from two of the people who built GitHub Copilot.",
    paid: true,
  },
  rlhfBook: {
    title: "Reinforcement Learning from Human Feedback",
    url: "https://rlhfbook.com/",
    kind: "book",
    source: "Nathan Lambert",
    year: 2025,
    note: "A free online book on RLHF, reward models, DPO and RL with verifiable rewards.",
  },

  // ── Docs & specs ──────────────────────────────────────────────────────────
  mcpDocs: {
    title: "What is the Model Context Protocol?",
    url: "https://modelcontextprotocol.io/docs/getting-started/intro",
    kind: "docs",
    source: "MCP",
    note: "The official docs: architecture, core concepts, and quickstarts for servers and clients.",
  },
  mcpSpec: {
    title: "MCP Specification (2026-07-28)",
    url: "https://modelcontextprotocol.io/specification/2026-07-28",
    kind: "docs",
    source: "MCP",
    year: 2026,
    note: "The current spec: stateless core, server/discover, multi round-trip requests, extensions and a formal deprecation policy.",
  },
  mcpChangelog: {
    title: "MCP 2026-07-28 Changelog",
    url: "https://modelcontextprotocol.io/specification/2026-07-28/changelog",
    kind: "docs",
    source: "MCP",
    year: 2026,
    note: "Exactly what changed from 2025-11-25: sessions and the initialize handshake removed; Roots, Sampling and Logging deprecated.",
  },
  mcpBuildServer: {
    title: "Build an MCP Server",
    url: "https://modelcontextprotocol.io/docs/develop/build-server",
    kind: "docs",
    source: "MCP",
    note: "The step-by-step server tutorial, in Python and the other official SDKs.",
  },
  mcpSecurity: {
    title: "MCP Security Best Practices",
    url: "https://modelcontextprotocol.io/docs/tutorials/security/security_best_practices",
    kind: "docs",
    source: "MCP",
    note: "Confused deputies, token passthrough, SSRF and session hijacking — the attacks to design against.",
  },
  a2aProtocol: {
    title: "Agent2Agent (A2A) Protocol",
    url: "https://a2a-protocol.org/latest/",
    kind: "docs",
    source: "A2A Project",
    year: 2025,
    note: "An open protocol for agents to discover each other through Agent Cards and collaborate on tasks across vendors.",
  },
  agentsMd: {
    title: "AGENTS.md",
    url: "https://agents.md/",
    kind: "docs",
    source: "Agentic AI Foundation",
    year: 2025,
    note: "A simple open format for giving coding agents project instructions — a README written for agents.",
  },
  langgraphDocs: {
    title: "LangGraph Overview",
    url: "https://docs.langchain.com/oss/python/langgraph/overview",
    kind: "docs",
    source: "LangChain",
    note: "Low-level orchestration for stateful, long-running agents: graphs, persistence, streaming, interrupts.",
  },
  langgraphPersistence: {
    title: "LangGraph Persistence",
    url: "https://docs.langchain.com/oss/python/langgraph/persistence",
    kind: "docs",
    source: "LangChain",
    note: "Checkpointers and threads — the basis for memory, human-in-the-loop, time travel and fault tolerance.",
  },
  langgraphInterrupts: {
    title: "LangGraph Interrupts",
    url: "https://docs.langchain.com/oss/python/langgraph/interrupts",
    kind: "docs",
    source: "LangChain",
    note: "Pause a graph mid-run for human input with interrupt(), then resume it with Command(resume=...).",
  },
  langchainMemory: {
    title: "Memory Overview",
    url: "https://docs.langchain.com/oss/python/concepts/memory",
    kind: "docs",
    source: "LangChain",
    note: "Short-term (thread) vs long-term (store) memory, and how semantic, episodic and procedural memory map onto agents.",
  },
  langchainMultiAgent: {
    title: "Multi-agent",
    url: "https://docs.langchain.com/oss/python/langchain/multi-agent",
    kind: "docs",
    source: "LangChain",
    note: "Supervisor, handoff and router patterns, with guidance on what context to pass between agents.",
  },
  openaiAgentsSdk: {
    title: "OpenAI Agents SDK",
    url: "https://openai.github.io/openai-agents-python/",
    kind: "docs",
    source: "OpenAI",
    note: "A small set of primitives — agents, tools, handoffs, guardrails, sessions — with tracing built in.",
  },
  openaiFunctionCalling: {
    title: "Function Calling",
    url: "https://platform.openai.com/docs/guides/function-calling",
    kind: "docs",
    source: "OpenAI",
    note: "The canonical reference for tool schemas, tool choice, parallel calls and strict mode.",
  },
  openaiStructuredOutputs: {
    title: "Structured Outputs",
    url: "https://platform.openai.com/docs/guides/structured-outputs",
    kind: "docs",
    source: "OpenAI",
    note: "Schema-constrained JSON output: the supported JSON Schema subset, refusals and edge cases.",
  },
  claudeToolUse: {
    title: "Tool Use with Claude",
    url: "https://platform.claude.com/docs/en/agents-and-tools/tool-use/overview",
    kind: "docs",
    source: "Anthropic",
    note: "Client and server tools, tool choice, parallel tool use and how to write good tool definitions.",
  },
  claudePromptEng: {
    title: "Prompt Engineering Overview",
    url: "https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview",
    kind: "docs",
    source: "Anthropic",
    note: "Clear instructions, examples, XML structure, chain-of-thought and long-context technique, with examples.",
  },
  claudeAgentSdk: {
    title: "Claude Agent SDK",
    url: "https://code.claude.com/docs/en/agent-sdk/overview",
    kind: "docs",
    source: "Anthropic",
    note: "The Claude Code harness as a library: file and shell tools, subagents, permissions, compaction and MCP.",
  },
  googleAdk: {
    title: "Agent Development Kit (ADK)",
    url: "https://adk.dev/",
    kind: "docs",
    source: "Google",
    note: "A code-first multi-agent framework with workflow agents (sequential, parallel, loop) and A2A support.",
  },
  msAgentFramework: {
    title: "Microsoft Agent Framework",
    url: "https://learn.microsoft.com/en-us/agent-framework/overview/",
    kind: "docs",
    source: "Microsoft",
    note: "The successor to AutoGen and Semantic Kernel: agents plus graph-based workflows, in Python and .NET.",
  },
  crewAiDocs: {
    title: "CrewAI",
    url: "https://docs.crewai.com/",
    kind: "docs",
    source: "CrewAI",
    note: "Role-based agent crews and event-driven flows — quick to stand up for multi-agent prototypes.",
  },
  pydanticAi: {
    title: "Pydantic AI",
    url: "https://pydantic.dev/docs/ai/overview/",
    kind: "docs",
    source: "Pydantic",
    note: "Type-safe agents with validated structured outputs and dependency injection, from the Pydantic team.",
  },
  smolagents: {
    title: "smolagents",
    url: "https://huggingface.co/docs/smolagents/index",
    kind: "docs",
    source: "Hugging Face",
    note: "A minimalist library whose code agents write Python actions instead of JSON tool calls.",
  },
  llamaIndexDocs: {
    title: "LlamaIndex",
    url: "https://developers.llamaindex.ai/python/framework/",
    kind: "docs",
    source: "LlamaIndex",
    note: "A data framework for RAG and agents over your documents: ingestion, indexing, query engines and workflows.",
  },
  instructor: {
    title: "Instructor",
    url: "https://python.useinstructor.com/",
    kind: "docs",
    source: "Instructor",
    note: "Pydantic-validated structured outputs with automatic retries, across most LLM providers.",
  },
  dspyDocs: {
    title: "DSPy",
    url: "https://dspy.ai/",
    kind: "docs",
    source: "Stanford NLP",
    note: "Program LLM pipelines as modules and let optimizers tune the prompts against your metric.",
  },
  groqToolUse: {
    title: "Tool Use on Groq",
    url: "https://console.groq.com/docs/tool-use",
    kind: "docs",
    source: "Groq",
    note: "OpenAI-compatible tool calling on Groq — the provider this app's backend already uses, so the code samples run as-is.",
  },
  langfuse: {
    title: "Langfuse",
    url: "https://langfuse.com/docs",
    kind: "docs",
    source: "Langfuse",
    note: "Open-source, self-hostable tracing, prompt management and evals.",
  },
  langsmith: {
    title: "LangSmith Observability",
    url: "https://docs.langchain.com/langsmith/observability",
    kind: "docs",
    source: "LangChain",
    note: "Tracing, datasets and evaluations with first-class LangGraph support; works without LangChain too.",
  },
  phoenix: {
    title: "Arize Phoenix",
    url: "https://arize.com/docs/phoenix",
    kind: "docs",
    source: "Arize",
    note: "Open-source, OpenTelemetry-based tracing and evaluation for LLM apps and agents.",
  },
  otelGenAI: {
    title: "OpenTelemetry GenAI Semantic Conventions",
    url: "https://github.com/open-telemetry/semantic-conventions-genai",
    kind: "docs",
    source: "OpenTelemetry",
    year: 2026,
    note: "The emerging standard attribute names for LLM, agent and tool spans — moved to its own repo in 2026, still in development.",
  },
  ragas: {
    title: "Ragas",
    url: "https://docs.ragas.io/en/stable/",
    kind: "docs",
    source: "Ragas",
    note: "Metrics and test-set generation for evaluating RAG pipelines and agents.",
  },
  promptfoo: {
    title: "promptfoo",
    url: "https://www.promptfoo.dev/docs/intro/",
    kind: "docs",
    source: "promptfoo",
    note: "Config-driven evals and red-teaming from the command line — easy to wire into CI.",
  },
  inspectAi: {
    title: "Inspect",
    url: "https://inspect.aisi.org.uk/",
    kind: "docs",
    source: "UK AI Security Institute",
    note: "A rigorous open-source framework for model and agent evals, with sandboxed tool execution.",
  },
  vllm: {
    title: "vLLM",
    url: "https://docs.vllm.ai/en/latest/",
    kind: "docs",
    source: "vLLM",
    note: "The standard open-source inference server: PagedAttention, continuous batching, an OpenAI-compatible API.",
  },
  hfPeft: {
    title: "PEFT",
    url: "https://huggingface.co/docs/peft/index",
    kind: "docs",
    source: "Hugging Face",
    note: "LoRA, QLoRA and other adapter methods for Hugging Face models.",
  },
  hfTrl: {
    title: "TRL",
    url: "https://huggingface.co/docs/trl/index",
    kind: "docs",
    source: "Hugging Face",
    note: "Trainers for SFT, DPO, GRPO and reward modeling.",
  },
  unsloth: {
    title: "Unsloth",
    url: "https://docs.unsloth.ai/",
    kind: "docs",
    source: "Unsloth",
    note: "Fast, memory-efficient LoRA and QLoRA fine-tuning (and RL) on a single GPU, with ready-made notebooks.",
  },
  owaspLlmTop10: {
    title: "OWASP Top 10 for LLM Applications",
    url: "https://genai.owasp.org/llm-top-10/",
    kind: "docs",
    source: "OWASP GenAI Security Project",
    year: 2025,
    note: "Prompt injection, sensitive information disclosure, excessive agency and the rest of the core LLM risk list.",
  },
  owaspAgentic: {
    title: "OWASP Top 10 for Agentic Applications (2026)",
    url: "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/",
    kind: "docs",
    source: "OWASP GenAI Security Project",
    year: 2025,
    note: "ASI01–ASI10: goal hijack, tool misuse, identity abuse, memory poisoning, cascading failures, rogue agents and more.",
  },
  nistAiRmf: {
    title: "AI Risk Management Framework",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
    kind: "docs",
    source: "NIST",
    note: "The govern / map / measure / manage frame that enterprise AI policies tend to build on.",
  },
  tenacity: {
    title: "Tenacity",
    url: "https://tenacity.readthedocs.io/en/latest/",
    kind: "docs",
    source: "Tenacity",
    note: "Retries with exponential backoff, jitter and stop conditions — the standard Python retry library.",
  },
  chromaDocs: {
    title: "Chroma",
    url: "https://docs.trychroma.com/docs/overview/introduction",
    kind: "docs",
    source: "Chroma",
    note: "The embedded vector store this app's System Design RAG runs on.",
  },
  mteb: {
    title: "MTEB Leaderboard",
    url: "https://huggingface.co/spaces/mteb/leaderboard",
    kind: "docs",
    source: "Hugging Face",
    note: "Embedding-model results by task — a prior for choosing an embedding model, never a verdict.",
  },
  bfcl: {
    title: "Berkeley Function Calling Leaderboard",
    url: "https://gorilla.cs.berkeley.edu/leaderboard.html",
    kind: "docs",
    source: "UC Berkeley (Gorilla)",
    note: "Function-calling accuracy across simple, parallel, multi-turn and should-not-call cases.",
  },
  sweBenchSite: {
    title: "SWE-bench Leaderboards",
    url: "https://www.swebench.com/",
    kind: "docs",
    source: "SWE-bench",
    note: "Current results for SWE-bench Verified and its other variants.",
  },
  terminalBench: {
    title: "Terminal-Bench",
    url: "https://www.tbench.ai/",
    kind: "docs",
    source: "Terminal-Bench",
    note: "Hard tasks completed in a real terminal — the benchmark for agents that work in the shell.",
  },

  // ── Tools & repos ─────────────────────────────────────────────────────────
  mcpPythonSdk: {
    title: "MCP Python SDK",
    url: "https://github.com/modelcontextprotocol/python-sdk",
    kind: "repo",
    source: "MCP",
    note: "The official Python SDK, including FastMCP for decorator-based servers.",
  },
  anthropicCookbook: {
    title: "Claude Cookbooks",
    url: "https://github.com/anthropics/claude-cookbooks",
    kind: "repo",
    source: "Anthropic",
    note: "Runnable notebooks for tool use, RAG, sub-agents, evals and the agent patterns.",
  },
  openaiCookbook: {
    title: "OpenAI Cookbook",
    url: "https://cookbook.openai.com/",
    kind: "repo",
    source: "OpenAI",
    note: "Worked examples for function calling, structured outputs, evals and agents.",
  },
  genaiAgents: {
    title: "GenAI Agents",
    url: "https://github.com/NirDiamant/GenAI_Agents",
    kind: "repo",
    source: "Nir Diamant",
    note: "50+ notebook tutorials for agent techniques, from simple bots to multi-agent systems.",
  },
  ragTechniques: {
    title: "RAG Techniques",
    url: "https://github.com/NirDiamant/RAG_Techniques",
    kind: "repo",
    source: "Nir Diamant",
    note: "Notebook implementations of dozens of RAG techniques, from chunking strategies to graph and agentic RAG.",
  },
  agentsTowardsProduction: {
    title: "Agents Towards Production",
    url: "https://github.com/NirDiamant/agents-towards-production",
    kind: "repo",
    source: "Nir Diamant",
    note: "Code-first tutorials for the production layer: memory, observability, security, deployment.",
  },
  mlabonneLlmCourse: {
    title: "LLM Course",
    url: "https://github.com/mlabonne/llm-course",
    kind: "repo",
    source: "Maxime Labonne",
    note: "Roadmaps and Colab notebooks spanning LLM fundamentals, fine-tuning and LLM engineering.",
  },
  llmsFromScratch: {
    title: "LLMs-from-scratch",
    url: "https://github.com/rasbt/LLMs-from-scratch",
    kind: "repo",
    source: "Sebastian Raschka",
    note: "Free code for Build a Large Language Model (From Scratch), plus bonus material on reasoning and fine-tuning.",
  },
  aieBookRepo: {
    title: "aie-book",
    url: "https://github.com/chiphuyen/aie-book",
    kind: "repo",
    source: "Chip Huyen",
    note: "Free companion resources for AI Engineering: chapter summaries, case studies and curated reading.",
  },
  pgvector: {
    title: "pgvector",
    url: "https://github.com/pgvector/pgvector",
    kind: "repo",
    source: "pgvector",
    note: "Vector similarity search inside Postgres — often all the vector database a team needs.",
  },
  nemoGuardrails: {
    title: "NeMo Guardrails",
    url: "https://github.com/NVIDIA-NeMo/Guardrails",
    kind: "repo",
    source: "NVIDIA",
    note: "Programmable input, output, dialog and retrieval rails for LLM applications.",
  },
  browserUse: {
    title: "Browser Use",
    url: "https://github.com/browser-use/browser-use",
    kind: "repo",
    source: "Browser Use",
    note: "An open-source library for agents that drive a real browser.",
  },
  letta: {
    title: "Letta (formerly MemGPT)",
    url: "https://github.com/letta-ai/letta",
    kind: "repo",
    source: "Letta",
    note: "Stateful agents with self-editing memory blocks — MemGPT's ideas turned into a platform.",
  },
  mem0: {
    title: "Mem0",
    url: "https://github.com/mem0ai/mem0",
    kind: "repo",
    source: "Mem0",
    note: "A memory layer that extracts, updates and retrieves user and agent memories across sessions.",
  },
  graphiti: {
    title: "Graphiti",
    url: "https://github.com/getzep/graphiti",
    kind: "repo",
    source: "Zep",
    note: "Temporal knowledge graphs for agent memory: facts with validity windows, not just vectors.",
  },

  // ── Follow ────────────────────────────────────────────────────────────────
  anthropicEngineeringBlog: {
    title: "Anthropic Engineering Blog",
    url: "https://www.anthropic.com/engineering",
    kind: "blog",
    source: "Anthropic",
    note: "Many of the most useful agent-engineering write-ups in this library first appeared here.",
  },
  simonWillisonBlog: {
    title: "Simon Willison's Weblog",
    url: "https://simonwillison.net/",
    kind: "blog",
    source: "Simon Willison",
    note: "Daily, hands-on notes on LLMs, tools and prompt-injection security.",
  },
  hamelBlog: {
    title: "Hamel's Blog",
    url: "https://hamel.dev/",
    kind: "blog",
    source: "Hamel Husain",
    note: "The go-to writing on evals and error analysis.",
  },
  eugeneYanBlog: {
    title: "Eugene Yan",
    url: "https://eugeneyan.com/",
    kind: "blog",
    source: "Eugene Yan",
    note: "Applied ML and LLM systems — evals, RAG, recommendations — always grounded in practice.",
  },
  lilianWengBlog: {
    title: "Lil'Log",
    url: "https://lilianweng.github.io/",
    kind: "blog",
    source: "Lilian Weng",
    note: "Long-form, research-dense surveys; each one saves weeks of paper reading.",
  },
  huyenBlog: {
    title: "Chip Huyen's Blog",
    url: "https://huyenchip.com/blog/",
    kind: "blog",
    source: "Chip Huyen",
    note: "Production-focused essays on AI systems and engineering.",
  },
  latentSpace: {
    title: "Latent Space",
    url: "https://www.latent.space/",
    kind: "blog",
    source: "swyx & Alessio Fanelli",
    note: "Podcast and newsletter for AI engineers — long interviews with the people building the tools.",
  },
  interconnects: {
    title: "Interconnects",
    url: "https://www.interconnects.ai/",
    kind: "blog",
    source: "Nathan Lambert",
    note: "Deep, opinionated coverage of post-training, RL and open models.",
  },
  raschkaMagazine: {
    title: "Ahead of AI",
    url: "https://magazine.sebastianraschka.com/",
    kind: "blog",
    source: "Sebastian Raschka",
    note: "Clear explanations of new LLM architectures, training methods and papers.",
  },
  theBatch: {
    title: "The Batch",
    url: "https://www.deeplearning.ai/the-batch",
    kind: "blog",
    source: "DeepLearning.AI",
    note: "Andrew Ng's weekly letter plus a digest of the week's AI news.",
  },
  langchainBlog: {
    title: "LangChain Blog",
    url: "https://www.langchain.com/blog",
    kind: "blog",
    source: "LangChain",
    note: "Agent patterns, context engineering and LangGraph releases.",
  },
  hfBlog: {
    title: "Hugging Face Blog",
    url: "https://huggingface.co/blog",
    kind: "blog",
    source: "Hugging Face",
    note: "Open models, libraries and agent research, usually with code.",
  },
} satisfies Record<string, TheoryResource>;

export type AgenticResourceId = keyof typeof R;

export const ALL_AGENTIC_RESOURCES: TheoryResource[] = Object.values(R);

// Display order for the library's kind groups and filter chips.
export const RESOURCE_KIND_ORDER: ResourceKind[] = ["guide", "paper", "course", "video", "book", "docs", "repo", "blog"];
